# -*- coding: utf-8 -*-
"""python code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnqE4NOQYS0F0ct4xUjJ6tpdL-4pwqav
"""

print("adding python code for the project")